spring:
  datasource:
    url: jdbc:postgresql://10.16.48.219:5432/software7  #10.16.48.219
    username: pg
    password: 111111  #111111
    driver-class-name: org.postgresql.Driver

#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/software7?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
gorit:
  file:
    root:
      path1: C:\Project\IdeaProject\software7\src\main\resources\file\
      path2: C:\Project\IdeaProject\software7\src\main\resources\algorithm\
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath: com/edu/cqupt/software7/mapper/*.xml
  type-aliases-package: com.edu.cqupt.software7.entity
server:
  port: 8088
application:
  python:
    emvironment: C:\DevelopmentTools\anaconda3\python.exe