spring:
  datasource:
    url: jdbc:mysql://localhost:3306/software7?characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小
gorit:
  file:
    root:
      path1: F:\java\medical\software7\src\main\resources\file\
      path2: F:\java\medical\software7\src\main\resources\algorithm\
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath: com/edu/cqupt/software7/mapper/*.xml
  type-aliases-package: com.edu.cqupt.software7.entity
server:
  port: 8088
application:
  python:
    emvironment: C:\Users\hp\anaconda3\python.exe